<?php
unset($Fid_db);
$Fid_db[1][3]='社会新闻';
		$Fid_db[name][3]='社会新闻';
		$Fid_db[11][12]='建站软件';
		$Fid_db[name][12]='建站软件';
		$Fid_db[15][16]='数码产品';
		$Fid_db[name][16]='数码产品';
		$Fid_db[11][26]='装机软件';
		$Fid_db[name][26]='装机软件';
		$Fid_db[11][27]='办公软件';
		$Fid_db[name][27]='办公软件';
		$Fid_db[1][33]='图片新闻';
		$Fid_db[name][33]='图片新闻';
		$Fid_db[1][35]='奇闻趣事';
		$Fid_db[name][35]='奇闻趣事';
		$Fid_db[1][38]='一语惊人';
		$Fid_db[name][38]='一语惊人';
		?>