<?php
		$webdb['yzImgComment']='0';
$webdb['flashtime']='0';
$webdb['showComment']='1';
$webdb['forbidComment']='0';
$webdb['showCommentRows']='8';
$webdb['viewNoPassGuestBook']='1';
$webdb['yzImgContribute']='0';
$webdb['groupPassContribute']='3';
$webdb['RegYz']='1';
$webdb['MaxOnlineUser']='1000';
$webdb['groupPassShopYz']='3,4';
$webdb['groupPassPassGuestBook']='3';
$webdb['ifOpenGuestBook']='1';
$webdb['yzImgGuestBook']='1';
$webdb['ContributeFid']='2';
$webdb['SPbencandy_filename']='html/5special{$fid}/show{$id}.htm';
$webdb['groupPassLogYz']='3,4';
$webdb['forbidRegName']='';
$webdb['FtpPort']='21';
$webdb['PostSortStep']='2';
$webdb['ListSonline']='2';
$webdb['_Notice']='29weSgiaHR0cDovL3d3dy5waHAxNjguY29tL05vdGljZS8/dXJsPSR3ZWJkYlt3d3dfdXJsXSIsUEhQMTY4X1BBVEguImNhY2hlL05vdGljZS5waHAiKTs=';
$webdb['CommentTime']='5';
$webdb['JsListRows']='5';
$webdb['JsListLeng']='36';
$webdb['ListSonRows']='9';
$webdb['ListSonLeng']='34';
$webdb['weburl']='/';
$webdb['MailType']='smtp';
$webdb['MailServer']='smtp.163.com';
$webdb['yeepay_id']='10000821064';
$webdb['yeepay_key']='ve4ets3huzxruch0tsf6nga7a2lpckm8h9p7qnefj31q49ms8bhl3qin6q0g';
$webdb['allowMemberCommentPass']='1';
$webdb['Listsortnameline']='2';
$webdb['AvoidGatherPre']='';
$webdb['AvoidCopy']='0';
$webdb['AvoidGather']='0';
$webdb['AvoidSave']='0';
$webdb['AvoidGatherString']='';
$webdb['waterpos']='7';
$webdb['adminPostEditType']='html';
$webdb['article_show_step']='0';
$webdb['ifContribute']='1';
$webdb['allowGuestSearch']='0';
$webdb['kill_badword']='0';
$webdb['KeepTodayCount']='0';
$webdb['close_count']='1';
$webdb['ShowKeywordColor']='#F70968';
$webdb['ifShowKeyword']='1';
$webdb['UseFtp']='0';
$webdb['FtpDir']='111';
$webdb['FtpWeb']='';
$webdb['FtpPwd']='admin';
$webdb['FtpName']='admin';
$webdb['ListLeng']='70';
$webdb['showsortlogo']='0';
$webdb['groupTime']='180';
$webdb['allowGuestCommentPass']='1';
$webdb['ShowMenu']='0';
$webdb['GuestBookNum']='8';
$webdb['ShopOtherSend']='18';
$webdb['ShopNormalSend']='8';
$webdb['ShopEmsSend']='25';
$webdb['groupUpType']='1';
$webdb['SideTitleStyle']='side_tpl/2';
$webdb['list_filename2']='list.php?fid-{$fid}-page-{$page}.htm';
$webdb['SPlist_filename']='html/4special{$fid}/list{$page}.htm';
$webdb['waterimg']='images/default/water.gif';
$webdb['HideNopowerPost']='1';
$webdb['listPicRows']='5';
$webdb['SideSortStyle']='side_sort/2';
$webdb['labelsort_show_step']='0';
$webdb['CommentOrderType']='0';
$webdb['showNoPassComment']='0';
$webdb['allowGuestComment']='1';
$webdb['TheSameMakeIndexHtml']='0';
$webdb['ArticleHeart']='欠扁|1.gif
支持|2.gif
很棒|3.gif
找骂|4.gif
搞笑|5.gif
软文|6.gif
不解|7.gif
吃惊|8.gif';
$webdb['heart_time']='30';
$webdb['heart_noRecord']='1';
$webdb['UseArticleHeart']='1';
$webdb['ForceDel']='0';
$webdb['propagandize_jumpto']='/';
$webdb['propagandize_LogDay']='5';
$webdb['propagandize_close']='0';
$webdb['propagandize_Money']='2';
$webdb['AutoTitleNum']='1';
$webdb['YZ_IdcardMoney']='20';
$webdb['EditYzEmail']='0';
$webdb['EditYzMob']='0';
$webdb['EditYzIdcard']='0';
$webdb['YZ_EmailMoney']='10';
$webdb['YZ_MobMoney']='15';
$webdb['MailPort']='25';
$webdb['sms_wi_id']='2';
$webdb['sms_wi_pwd']='3';
$webdb['sms_es_key']='2';
$webdb['sms_es_name']='1';
$webdb['sms_type']='winic';
$webdb['bencandy_filename2']='bencandy.php?fid-{$fid}-id-{$id}-page-{$page}.htm';
$webdb['SPlist_filename2']='listsp.php?fid-{$fid}-page-{$page}.htm';
$webdb['ForbidIp']='';
$webdb['AdminIp']='';
$webdb['AllowVisitIp']='';
$webdb['BbsUserAutoPass']='1';
$webdb['emailOnly']='1';
$webdb['ForbidCountDomain']='';
$webdb['Reg_Field']='a:1:{s:8:\\\\\\\\\\\\\\\\\\\"field_db\\\\\\\\\\\\\\\\\\\";N;}';
$webdb['1']='8';
$webdb['0']='4';
$webdb['passport_TogetherLogin']='1';
$webdb['deleteArticleMoney']='-1';
$webdb['postArticleMoney']='1';
$webdb['comArticleMoney']='3';
$webdb['hotArticleNum']='100';
$webdb['newArticleTime']='24';
$webdb['ListShowIcon']='0';
$webdb['autoGetKeyword']='0';
$webdb['tenpay_id']='fdsafdsa';
$webdb['tenpay_key']='fdsafds';
$webdb['alipay_id']='test@test.com';
$webdb['RegCompany']='1';
$webdb['cache_time_js']='-1';
$webdb['fulist_cache_time']='';
$webdb['autoGetSmallPic']='1';
$webdb['autoCutSmallPic']='1';
$webdb['ForbidRepeatTitle']='1';
$webdb['viewNoPassArticle']='0';
$webdb['ArticleDownloadUseFtp']='0';
$webdb['ArticleDownloadDirTime']='0';
$webdb['ArticlePicWidth']='800';
$webdb['ArticlePicHeight']='600';
$webdb['SortUseOtherModule']='1';
$webdb['ForbidShowPhpPage']='0';
$webdb['SPbencandy_filename2']='showsp.php?fid-{$fid}-id-{$id}-page-{$page}.htm';
$webdb['list_filename']='html/{$fid}/{$page}.htm';
$webdb['bencandy_filename']='html/{$fid}-{$dirid}/{$id}-{$page}.htm';
$webdb['cache_time_com']='-1';
$webdb['PostNotice']='<font face=SimSun>
<p><font face=SimSun>1、如果是转载内容，请务必填写稿件来源网址及出处。<br />2、所引起的版权纠纷与法律责任由发布者承担。</font></p></font>';
$webdb['allowDownMv']='0';
$webdb['autoPlayFirstMv']='1';
$webdb['XunLei_ID']='08311';
$webdb['FlashGet_ID']='6370';
$webdb['forbidRegIp']='';
$webdb['sortNUM']='27';
$webdb['hideFid']='';
$webdb['FtpHost']='127.0.0.1';
$webdb['articleNUM']='388';
$webdb['miibeian_gov_cn']='京ICP备050453号';
$webdb['path']='/do';
$webdb['AutoPassCompany']='1';
$webdb['memberNotice']='欢迎大家踊跃投稿,投稿可得积分奖励!!';
$webdb['AutoCutFace']='0';
$webdb['yzImgAdminLogin']='0';
$webdb['Del_MoreUpfile']='1';
$webdb['DownLoad_readfile']='1';
$webdb['cache_time_like']='-1';
$webdb['cache_time_new']='-1';
$webdb['is_waterimg']='1';
$webdb['passport_path']='../pw7';
$webdb['companyTrade']='机械及行业设备
普通机械制造
通用零部件
五金配件
金属工具
电动工具
电子元件
电子器件
照明及照明器具
安全防护设备
包装
造纸及纸制品
电机、电工电器
电工器材
通用仪器仪表
专用仪器仪表
交通运输设备、零部件
办公、文教用品
数码、电脑及网络配件
日常家居用品
木材、木制品
家具
家用电器
礼品、工艺美术品
食品、饮料
通信产品
玩具
印刷设备
运动、休闲、保健用品
鞋、帽
服装
日用化学品
农用化学品
胶粘剂
染料、颜料、涂料和油墨
催化剂和助剂
库存精细化学品
食品和饲料添加剂
塑料
橡胶制品
环保、环保设备
建筑、建材
能源
粮油、农制品
金属
医药、保健及医疗设备
纺织
皮革
煤焦化产品
日常服务
广告服务
教育培训
认证
创意设计
物流服务
进出口代理
维修及安装服务
广告、展览器材
专业录音、放音设备
光学摄影器材
编辑制作设备
播出、前端设备
建筑、装饰业
房地产
安装工程
邮电通信
事务所、公证
卫生、体育、社会、福利
公共服务业
金融、保险
实业公司、商业贸易
高新技术开发区
卡类市场';
$webdb['mymd5']='6166925';
$webdb['copyright']='';
$webdb['bokecc_id']='';
$webdb['cookieDomain']='';
$webdb['forbid_show_bug']='1';
$webdb['passport_type']='0';
$webdb['label_cache_time']='-1';
$webdb['mirror']='http://down2.php168.com/other/testv6/upload_files/';
$webdb['updir']='upload_files';
$webdb['upfileMaxSize']='';
$webdb['upfileType']='.rar .txt .jpg .gif .bmp .png .zip .mp3 .wma .wmv .mpeg .mpg .rm .ram .htm .doc .swf .avi .flv .sql .doc .ppt .xls .chm .pdf';
$webdb['passport_url']='http://www.7203850.com/';
$webdb['MailId']='lfj846@163.com';
$webdb['MailPw']='o6351,';
$webdb['totalSpace']='100';
$webdb['time']='0';
$webdb['NewsMakeHtml']='0';
$webdb['MakeIndexHtmlTime']='0';
$webdb['admin_url']='admin';
$webdb['www_url']='http://www.7203850.com';
$webdb['style']='default';
$webdb['close_why']='网站维护当中,
暂停访问.';
$webdb['web_open']='1';
$webdb['MoneyDW']='个';
$webdb['MoneyName']='整站积分';
$webdb['UserEmailAutoPass']='1';
$webdb['BuySpacesizeMoney']='50';
$webdb['UseMoneyType']='cms';
$webdb['webmail']='weiqk@hotmail.com';
$webdb['passport_pre']='`dz7`.cdb_';
$webdb['guide_word']='首页|/|0||51
新闻|list.php?fid=1|0||9
图片|list.php?fid=9|0||10
下载|list.php?fid=11|0||11
影视|list.php?fid=13|0||12
商城|list.php?fid=15|0||13
FLASH|list.php?fid=17|0||14
产品|list.php?fid=29|0||52
考评|/do/exam_write.php?id=3|0||54
DZ论坛|http://localhost/dz7/bbs|1||55
uch|http://localhost/dz7/uch/|1||56
ss|http://localhost/dz7/ss|1||57
pw|http://localhost/pw7|1||58';
$webdb['cache_time_pic']='-1';
$webdb['list_cache_time']='0';
$webdb['bencandy_cache_time']='0';
$webdb['showsp_cache_time']='0';
$webdb['description']='整站系统';
$webdb['metakeywords']='php168 news bbs board php mysql forums';
$webdb['cache_time_hot']='-1';
$webdb['forbidReg']='0';
$webdb['limitRegTime']='';
$webdb['yzImgReg']='1';
$webdb['pay99_id']='';
$webdb['pay99_key']='';
$webdb['alipay_scale']='10';
$webdb['MoneyRatio']='100';
$webdb['Money2card']='0';
$webdb['index_cache_time']='0';
$webdb['waterAlpha']='80';
$webdb['if_gdimg']='1';
$webdb['regmoney']='5';
$webdb['DefaultIndexHtml']='0';
$webdb['webname']='PHP168整站系统';
$webdb['reg_group']='8';
